package auth

import (
	"bytes"
	"errors"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/crypto/bcrypt"
)

// These hashes were produced by the `bcrypt-ts` package (v8.0.1) — the same
// library `website/` uses — via:
//
//	cd website && node --input-type=module -e \
//	  'import * as b from "bcrypt-ts"; console.log(await b.hash(<password>, 12));'
//
// They are committed verbatim so the test asserts a stable, real-world hash
// shape (cost 12, $2b$ prefix) is verifiable by golang.org/x/crypto/bcrypt.
// Regenerate if you ever change BCRYPT_ROUNDS.
type bcryptCase struct {
	label    string
	password string
	hash     string
}

var tsHashFixtures = []bcryptCase{
	{
		label:    "simple_ascii",
		password: "password123",
		hash:     "$2b$12$XrfHcigYkV4cgC4zCcXOUeJVUgXLeke.jrvM8/U8Hv/OyhOKKCWzC",
	},
	{
		label:    "empty_string",
		password: "",
		hash:     "$2b$12$QHwzhZnEUyerR85UQhBy.OhPQscx2VL6b847V1s2ftckohPtm.0Ae",
	},
	{
		label:    "unicode_vietnamese_plus_emoji",
		password: "Mật khẩu 🔒",
		hash:     "$2b$12$7JDkjLroi93.vctCaQU.F.jU89cVObIck5ww7304bygCDJgwXUCKq",
	},
	{
		label:    "long_84_bytes_truncated_to_72",
		password: strings.Repeat("a", 72) + "BBBBBBBBBBBB",
		hash:     "$2b$12$HT3/vjF1gKukoWVOoNmcC.rA8IPMq3dIqpGaKPHAPZcspiAgAZw4G",
	},
	{
		label:    "single_char",
		password: "x",
		hash:     "$2b$12$MM3qhEyh6fFmcED11KTq.Ogx9kHO2GJxkOXJwwxbE/VWzCTuXnirm",
	},
}

// TestBcryptCompat_TsHashGoVerify is the load-bearing direction: every existing
// user in the Postgres DB has a hash produced by bcrypt-ts. Once auth moves to
// the Go server, golang.org/x/crypto/bcrypt must verify those hashes against
// the user-supplied plaintext. If this test ever fails, do NOT ship the auth
// migration — investigate prefix / encoding differences first.
func TestBcryptCompat_TsHashGoVerify(t *testing.T) {
	for _, tc := range tsHashFixtures {
		tc := tc
		t.Run(tc.label, func(t *testing.T) {
			if err := bcrypt.CompareHashAndPassword([]byte(tc.hash), []byte(tc.password)); err != nil {
				t.Fatalf("Go failed to verify TS-produced hash: %v\n  hash=%q\n  password=%q", err, tc.hash, tc.password)
			}
			// Sanity: wrong password must reject. Mutate the first byte so the
			// 72-byte truncation window can't mask the difference (appending
			// to an already-72+ byte password would be a no-op after trunc).
			wrong := []byte(tc.password)
			if len(wrong) == 0 {
				wrong = []byte("!")
			} else {
				wrong = append([]byte{wrong[0] ^ 0x01}, wrong[1:]...)
			}
			if err := bcrypt.CompareHashAndPassword([]byte(tc.hash), wrong); !errors.Is(err, bcrypt.ErrMismatchedHashAndPassword) {
				t.Fatalf("expected mismatch error for wrong password, got %v", err)
			}
		})
	}
}

// TestBcryptCompat_TsHashPrefixIs2b documents that bcrypt-ts always emits the
// $2b$ variant. Go's bcrypt accepts both $2a$ and $2b$ (and $2y$), so this is
// informational — but if bcrypt-ts ever switches prefixes we want to notice.
func TestBcryptCompat_TsHashPrefixIs2b(t *testing.T) {
	for _, tc := range tsHashFixtures {
		if !strings.HasPrefix(tc.hash, "$2b$12$") {
			t.Errorf("%s: expected $2b$12$ prefix, got %q", tc.label, tc.hash[:7])
		}
	}
}

// TestBcryptCompat_TruncationParity locks in that both libraries truncate at
// 72 bytes. We verify a 72-byte password against a hash generated by bcrypt-ts
// from an 84-byte string that shares the same first 72 bytes — if either
// library disagreed about truncation, this would fail.
func TestBcryptCompat_TruncationParity(t *testing.T) {
	var tc bcryptCase
	for _, c := range tsHashFixtures {
		if c.label == "long_84_bytes_truncated_to_72" {
			tc = c
			break
		}
	}
	if tc.hash == "" {
		t.Fatal("fixture missing")
	}
	first72 := strings.Repeat("a", 72)
	if err := bcrypt.CompareHashAndPassword([]byte(tc.hash), []byte(first72)); err != nil {
		t.Fatalf("Go did not treat 84-byte and 72-byte passwords as equivalent: %v", err)
	}
	// And the full 84-byte string also matches (trivially, since bcrypt-ts
	// produced it from the 84-byte input).
	if err := bcrypt.CompareHashAndPassword([]byte(tc.hash), []byte(tc.password)); err != nil {
		t.Fatalf("Go did not verify the original 84-byte password: %v", err)
	}
	// But differing the first 72 bytes must fail.
	differentFirst72 := "Z" + strings.Repeat("a", 71)
	if err := bcrypt.CompareHashAndPassword([]byte(tc.hash), []byte(differentFirst72)); err == nil {
		t.Fatal("expected mismatch when first 72 bytes differ, got nil")
	}
}

// TestBcryptCompat_GoHashTsVerify is the reverse direction: hashes produced by
// the Go server (for new signups or password resets) must be verifiable by
// bcrypt-ts in case anyone ever has to fall back to the web service or run a
// legacy script. We shell out to node + bcrypt-ts via testdata/verify.mjs.
//
// Skipped if node or the bcrypt-ts package isn't available in this checkout.
func TestBcryptCompat_GoHashTsVerify(t *testing.T) {
	nodePath, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node not on PATH; skipping reverse-direction compat check")
	}
	script, err := filepath.Abs(filepath.Join("testdata", "verify.mjs"))
	if err != nil {
		t.Fatalf("abs path: %v", err)
	}
	btsPkg, err := filepath.Abs(filepath.Join("..", "..", "..", "website", "node_modules", "bcrypt-ts"))
	if err != nil {
		t.Fatalf("abs path: %v", err)
	}
	// Best-effort check that bcrypt-ts is installed.
	if _, err := exec.Command("test", "-d", btsPkg).Output(); err != nil {
		t.Skipf("bcrypt-ts not installed at %s; run `npm install` in website/ to enable this test", btsPkg)
	}

	// Note: golang.org/x/crypto/bcrypt refuses to hash inputs longer than 72
	// bytes (returns ErrPasswordTooLong) — unlike bcrypt-ts, which silently
	// truncates. See TestBcryptCompat_GoRefusesOver72Bytes below. So in this
	// reverse-direction test we only feed Go inputs <=72 bytes; the migration
	// must either reject >72-byte passwords at the handler layer or truncate
	// before calling bcrypt.GenerateFromPassword.
	passwords := []string{
		"password123",
		"",
		"Mật khẩu 🔒",
		strings.Repeat("a", 72), // exactly at the limit
		"x",
	}

	for _, pw := range passwords {
		pw := pw
		t.Run("verify_via_bcrypt_ts", func(t *testing.T) {
			h, err := bcrypt.GenerateFromPassword([]byte(pw), 12)
			if err != nil {
				t.Fatalf("Go bcrypt.GenerateFromPassword: %v", err)
			}
			// Positive case.
			cmd := exec.Command(nodePath, script, string(h))
			cmd.Stdin = bytes.NewReader([]byte(pw))
			var stderr bytes.Buffer
			cmd.Stderr = &stderr
			if err := cmd.Run(); err != nil {
				t.Fatalf("bcrypt-ts rejected Go-produced hash for password %q: %v\nstderr: %s\nhash: %s",
					pw, err, stderr.String(), string(h))
			}
			// Negative case: wrong password must produce exit 1, not 2.
			// Mutate the first byte so bcrypt's 72-byte truncation can't hide
			// the difference (appending to a 72-byte input is a no-op after
			// truncation).
			wrong := []byte(pw)
			if len(wrong) == 0 {
				wrong = []byte("!")
			} else {
				wrong = append([]byte{wrong[0] ^ 0x01}, wrong[1:]...)
			}
			cmd = exec.Command(nodePath, script, string(h))
			cmd.Stdin = bytes.NewReader(wrong)
			stderr.Reset()
			cmd.Stderr = &stderr
			err = cmd.Run()
			var exitErr *exec.ExitError
			if !errors.As(err, &exitErr) || exitErr.ExitCode() != 1 {
				t.Fatalf("expected exit code 1 for wrong password, got err=%v stderr=%s", err, stderr.String())
			}
		})
	}
}

// auth.Hash truncates to 72 bytes before calling bcrypt.GenerateFromPassword
// to match bcrypt-ts behavior. This test pins that down: raw
// bcrypt.GenerateFromPassword rejects >72 bytes since the 2024 hardening,
// but auth.Hash must accept and produce a hash that verifies against the
// first-72-bytes prefix.
func TestBcryptCompat_Over72BytesTruncatedByAuthHash(t *testing.T) {
	long := strings.Repeat("a", 73)

	if _, err := bcrypt.GenerateFromPassword([]byte(long), 12); !errors.Is(err, bcrypt.ErrPasswordTooLong) {
		t.Fatalf("raw bcrypt should reject 73-byte input; got %v", err)
	}

	hash, err := Hash(long)
	if err != nil {
		t.Fatalf("auth.Hash should accept 73-byte input via truncation; got %v", err)
	}

	if !Verify(long, hash) {
		t.Fatal("auth.Verify failed for the same long password that hashed")
	}
	if !Verify(strings.Repeat("a", 72), hash) {
		t.Fatal("auth.Verify should accept the 72-byte prefix of the long password")
	}
	if Verify(strings.Repeat("a", 71), hash) {
		t.Fatal("auth.Verify should reject a 71-byte prefix")
	}
}
